[package]
name = "ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "imffi"
crate-type = ["staticlib", "cdylib"]

[dependencies]
im = { path = '../im'}
libc = "0.2"
rand = "*"